/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simplekalkulator;

/**
 *
 * @author HP 245-G7
 */
public class Kalkulator extends javax.swing.JFrame {
    String angka;
    double jumlah, bil1,bil2;
    int pilih;
    boolean setelahSamaDitekan = false;

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
        angka = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tampil = new javax.swing.JTextField();
        Bc = new javax.swing.JButton();
        B0 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        Bper = new javax.swing.JButton();
        Btitik = new javax.swing.JButton();
        Bbagi = new javax.swing.JButton();
        Bkali = new javax.swing.JButton();
        Bmin = new javax.swing.JButton();
        Bplus = new javax.swing.JButton();
        Bsama = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.black);
        setResizable(false);

        tampil.setEditable(false);
        tampil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tampil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        Bc.setBackground(new java.awt.Color(51, 51, 51));
        Bc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bc.setForeground(new java.awt.Color(255, 255, 255));
        Bc.setText("C");
        Bc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcActionPerformed(evt);
            }
        });

        B0.setBackground(new java.awt.Color(51, 51, 51));
        B0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B0.setForeground(new java.awt.Color(255, 255, 255));
        B0.setText("0");
        B0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0ActionPerformed(evt);
            }
        });

        B1.setBackground(new java.awt.Color(51, 51, 51));
        B1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B1.setForeground(new java.awt.Color(255, 255, 255));
        B1.setText("1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setBackground(new java.awt.Color(51, 51, 51));
        B2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B2.setForeground(new java.awt.Color(255, 255, 255));
        B2.setText("2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setBackground(new java.awt.Color(51, 51, 51));
        B3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B3.setForeground(new java.awt.Color(255, 255, 255));
        B3.setText("3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B4.setBackground(new java.awt.Color(51, 51, 51));
        B4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B4.setForeground(new java.awt.Color(255, 255, 255));
        B4.setText("4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setBackground(new java.awt.Color(51, 51, 51));
        B5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B5.setForeground(new java.awt.Color(255, 255, 255));
        B5.setText("5");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setBackground(new java.awt.Color(51, 51, 51));
        B6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B6.setForeground(new java.awt.Color(255, 255, 255));
        B6.setText("6");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        B7.setBackground(new java.awt.Color(51, 51, 51));
        B7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B7.setForeground(new java.awt.Color(255, 255, 255));
        B7.setText("7");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        B8.setBackground(new java.awt.Color(51, 51, 51));
        B8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B8.setForeground(new java.awt.Color(255, 255, 255));
        B8.setText("8");
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        B9.setBackground(new java.awt.Color(51, 51, 51));
        B9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B9.setForeground(new java.awt.Color(255, 255, 255));
        B9.setText("9");
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        Bper.setBackground(new java.awt.Color(51, 51, 51));
        Bper.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bper.setForeground(new java.awt.Color(255, 255, 255));
        Bper.setText("%");
        Bper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BperActionPerformed(evt);
            }
        });

        Btitik.setBackground(new java.awt.Color(51, 51, 51));
        Btitik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btitik.setForeground(new java.awt.Color(255, 255, 255));
        Btitik.setText(".");
        Btitik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtitikActionPerformed(evt);
            }
        });

        Bbagi.setBackground(new java.awt.Color(51, 51, 51));
        Bbagi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bbagi.setForeground(new java.awt.Color(255, 255, 255));
        Bbagi.setText("/");
        Bbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbagiActionPerformed(evt);
            }
        });

        Bkali.setBackground(new java.awt.Color(51, 51, 51));
        Bkali.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bkali.setForeground(new java.awt.Color(255, 255, 255));
        Bkali.setText("x");
        Bkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkaliActionPerformed(evt);
            }
        });

        Bmin.setBackground(new java.awt.Color(51, 51, 51));
        Bmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bmin.setForeground(new java.awt.Color(255, 255, 255));
        Bmin.setText("-");
        Bmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BminActionPerformed(evt);
            }
        });

        Bplus.setBackground(new java.awt.Color(51, 51, 51));
        Bplus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bplus.setForeground(new java.awt.Color(255, 255, 255));
        Bplus.setText("+");
        Bplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BplusActionPerformed(evt);
            }
        });

        Bsama.setBackground(new java.awt.Color(255, 102, 0));
        Bsama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bsama.setText("=");
        Bsama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btitik, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bsama, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bplus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tampil, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bper, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bkali, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bmin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tampil, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bper, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bkali, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bmin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bplus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bsama, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btitik, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        angka += "4";
        tampil.setText(angka);
    }//GEN-LAST:event_B4ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        angka += "6";
        tampil.setText(angka);
    }//GEN-LAST:event_B6ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        angka += "9";
        tampil.setText(angka);
    }//GEN-LAST:event_B9ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        angka += "7";
        tampil.setText(angka);
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        angka += "8";
        tampil.setText(angka);
    }//GEN-LAST:event_B8ActionPerformed

    private void BtitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtitikActionPerformed
        if (!angka.contains(".")) {
        angka += ".";
        tampil.setText(angka);
        }
    }//GEN-LAST:event_BtitikActionPerformed

    private void BcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcActionPerformed
        tampil.setText("");
        angka = "";
        bil1 = 0.0;
        bil2 = 0.0;
        jumlah = 0.0;
        pilih = 0;
    }//GEN-LAST:event_BcActionPerformed

    private void B0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0ActionPerformed
        angka += "0";
        tampil.setText(angka);
    }//GEN-LAST:event_B0ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        angka += "1";
        tampil.setText(angka);
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        angka += "2";
        tampil.setText(angka);
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        angka += "3";
        tampil.setText(angka);
    }//GEN-LAST:event_B3ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        angka += "5";
        tampil.setText(angka);
    }//GEN-LAST:event_B5ActionPerformed

    private void BplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BplusActionPerformed

        if (!angka.isEmpty()) {
            if (pilih == 0) {
                bil1 = Double.parseDouble(angka);
            } else {
                bil2 = Double.parseDouble(angka);
                switch (pilih) {
                    case 1:
                        jumlah = bil1 + bil2;
                        break;
                    case 2:
                        jumlah = bil1 - bil2;
                        break;
                    case 3:
                        jumlah = bil1 * bil2;
                        break;
                    case 4:
                        jumlah = bil1 / bil2;
                        break;
                    case 5:
                        jumlah = bil1 / 100;
                        break;
                    default:
                        break;
                }
                
                String hasil = (jumlah % 1 == 0) ? String.valueOf((int) jumlah) : String.valueOf(jumlah);
                tampil.setText(hasil);

                bil1 = jumlah;
                angka = "";
                pilih = 0;
            }
            tampil.setText("+");
            angka = "";
            pilih = 1;
        }
        
        Bplus.setEnabled(true);
        Bmin.setEnabled(true);
        Bkali.setEnabled(true);
        Bbagi.setEnabled(true);
        Bsama.setEnabled(true);
        
    }//GEN-LAST:event_BplusActionPerformed

    private void BminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BminActionPerformed

       if (!angka.isEmpty()) {
            if (pilih == 0) {
                bil1 = Double.parseDouble(angka);
            } else {
                bil2 = Double.parseDouble(angka);
                switch (pilih) {
                    case 1:
                        jumlah = bil1 + bil2;
                        break;
                    case 2:
                        jumlah = bil1 - bil2;
                        break;
                    case 3:
                        jumlah = bil1 * bil2;
                        break;
                    case 4:
                        jumlah = bil1 / bil2;
                        break;
                    case 5:
                        jumlah = bil1 / 100;
                        break;
                    default:
                        break;
                }
                
                String hasil = (jumlah % 1 == 0) ? String.valueOf((int) jumlah) : String.valueOf(jumlah);
                tampil.setText(hasil);

                bil1 = jumlah;
                angka = "";
                pilih = 0;
            }
            tampil.setText("-");
            angka = "";
            pilih = 2;
        }
       Bplus.setEnabled(true);
       Bmin.setEnabled(true);
       Bkali.setEnabled(true);
       Bbagi.setEnabled(true);
       Bsama.setEnabled(true);
    }//GEN-LAST:event_BminActionPerformed

    private void BkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkaliActionPerformed

        if (!angka.isEmpty()) {
            if (pilih == 0) {
                bil1 = Double.parseDouble(angka);
            } else {
                bil2 = Double.parseDouble(angka);
                switch (pilih) {
                    case 1:
                        jumlah = bil1 + bil2;
                        break;
                    case 2:
                        jumlah = bil1 - bil2;
                        break;
                    case 3:
                        jumlah = bil1 * bil2;
                        break;
                    case 4:
                        jumlah = bil1 / bil2;
                        break;
                    case 5:
                        jumlah = bil1 / 100;
                        break;
                    default:
                        break;
                }
                
                String hasil = (jumlah % 1 == 0) ? String.valueOf((int) jumlah) : String.valueOf(jumlah);
                tampil.setText(hasil);

                bil1 = jumlah;
                angka = "";
                pilih = 0;
            }
            tampil.setText("x");
            angka = "";
            pilih = 3;
        }
        Bplus.setEnabled(true);
        Bmin.setEnabled(true);
        Bkali.setEnabled(true);
        Bbagi.setEnabled(true);
        Bsama.setEnabled(true);
    }//GEN-LAST:event_BkaliActionPerformed

    private void BbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbagiActionPerformed
        if (!angka.isEmpty()) {
            if (pilih == 0) {
                bil1 = Double.parseDouble(angka);
            } else {
                bil2 = Double.parseDouble(angka);
                switch (pilih) {
                    case 1:
                        jumlah = bil1 + bil2;
                        break;
                    case 2:
                        jumlah = bil1 - bil2;
                        break;
                    case 3:
                        jumlah = bil1 * bil2;
                        break;
                    case 4:
                        jumlah = bil1 / bil2;
                        break;
                    case 5:
                        jumlah = bil1 / 100;
                        break;
                    default:
                        break;
                }
                
                String hasil = (jumlah % 1 == 0) ? String.valueOf((int) jumlah) : String.valueOf(jumlah);
                tampil.setText(hasil);

                bil1 = jumlah;
                angka = "";
                pilih = 0;
            }
            tampil.setText("/");
            angka = "";
            pilih = 4;
        }
        Bplus.setEnabled(true);
        Bmin.setEnabled(true);
        Bkali.setEnabled(true);
        Bbagi.setEnabled(true);
        Bsama.setEnabled(true);
    }//GEN-LAST:event_BbagiActionPerformed

    private void BsamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsamaActionPerformed
        switch (pilih) {
            case 1:
                bil2 = Double.parseDouble(angka);
                jumlah = bil1 + bil2;
                break;
            case 2:
                bil2 = Double.parseDouble(angka);
                jumlah = bil1 - bil2;
                break;
            case 3:
                bil2 = Double.parseDouble(angka);
                jumlah = bil1 * bil2;
                break;
            case 4:
                bil2 = Double.parseDouble(angka);
                if (bil2 != 0) {
                    jumlah = bil1 / bil2;
                } else {
                    tampil.setText("Tidak Terdefinisi / Error");
                    return;
                }
                break;
            case 5:
                jumlah = bil1 / 100;
                break;
            default:
                break;
        }

        String hasil = (jumlah % 1 == 0) ? String.valueOf((int) jumlah) : String.valueOf(jumlah);
        tampil.setText(hasil);

        angka = hasil;
        pilih = 0;
        
        Bplus.setEnabled(true);
        Bmin.setEnabled(true);
        Bkali.setEnabled(true);
        Bbagi.setEnabled(true);
        Bsama.setEnabled(false);
        
        setelahSamaDitekan = true;
    }//GEN-LAST:event_BsamaActionPerformed

    private void BperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BperActionPerformed
        bil1 = Double.parseDouble(angka);
        tampil.setText("%");
        angka = "";
        pilih = 5;
        Bplus.setEnabled(true);
        Bmin.setEnabled(true);
        Bkali.setEnabled(true);
        Bbagi.setEnabled(true);
        Bsama.setEnabled(true);
    }//GEN-LAST:event_BperActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B0;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton Bbagi;
    private javax.swing.JButton Bc;
    private javax.swing.JButton Bkali;
    private javax.swing.JButton Bmin;
    private javax.swing.JButton Bper;
    private javax.swing.JButton Bplus;
    private javax.swing.JButton Bsama;
    private javax.swing.JButton Btitik;
    private javax.swing.JTextField tampil;
    // End of variables declaration//GEN-END:variables
}
